# This is a basic workflow to help you get started with Actions

name: Variable substitution.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Organice project
  setup-app:
    if: github.ref == 'refs/heads/master'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set env variables.
        run: |
          export REPO_NAME=${{ github.event.repository.name }}
          export SELECTED_APP="fastapi-app"
      - name: Setup app.
        run: |
          find ./ -maxdepth 1 -type f -exec rm -iv {} \
          rm -fr ./.github
          mv ./$SELECTED_APP/* ./
          rm -fr ./templates
      - name: Replace variables.
        run: |
          sed -e "s/\${{REPO_NAME}}/$REPO_NAME/" README.md
